# Generated by Django 4.1 on 2022-08-09 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postComment',
            new_name='blogComment',
        ),
    ]
