# Generated by Django 4.1 on 2022-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_postcomment_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
