# Generated by Django 4.1 on 2022-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('backup_email', models.CharField(blank=True, max_length=150)),
                ('another_phone', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('pic', models.ImageField(blank=True, default='static/img/user.png', upload_to='')),
                ('dob', models.DateTimeField(blank=True)),
            ],
        ),
    ]
